import { Injectable, inject } from '@angular/core';
import { HttpAgent, AgentSubscriber } from '@ag-ui/client';
import { ChatStateService } from './chat-state.service';
import { SharedStateService } from './shared-state.service';
import { A2UIEventService } from './a2ui-event.service';
import { environment } from '../../../environments/environment';

/**
 * AgUiService
 *
 * Wraps @ag-ui/client HttpAgent and bridges AG-UI events to Angular signals.
 * Orchestrates all agent communication via SSE streaming.
 *
 * CRITICAL SERVICE: All agent interactions flow through here.
 */
@Injectable({
  providedIn: 'root',
})
export class AgUiService {
  private chatState = inject(ChatStateService);
  private sharedState = inject(SharedStateService);
  private a2uiEventService = inject(A2UIEventService);

  private agent: HttpAgent;
  private streamTimeout: ReturnType<typeof setTimeout> | null = null;
  private readonly STREAM_TIMEOUT_MS = 180_000; // 3 minutes

  constructor() {
    // Initialize the HttpAgent — threadId is auto-generated by the library (uuid v4)
    this.agent = new HttpAgent({
      url: `${environment.apiUrl}${environment.agentEndpoint}`,
      headers: { 'X-User-Id': environment.userId },
    });
  }

  /** Current thread ID from the underlying HttpAgent */
  get threadId(): string {
    return this.agent.threadId;
  }

  /**
   * Run the agent with current messages and shared state
   * Uses HttpAgent from @ag-ui/client to handle request formatting
   */
  async runAgent(): Promise<void> {
    try {
      // Recreate agent with preserved threadId. Backend uses persisted history,
      // so we only send the latest user message (not full conversation).
      const threadId = this.agent.threadId;
      const latestUserMsg = this.chatState
        .messages()
        .filter((msg) => msg.role === 'user')
        .slice(-1)
        .map((msg) => ({
          id: msg.id,
          role: 'user' as const,
          content: [{ type: 'text' as const, text: msg.content }],
        }));

      this.agent = new HttpAgent({
        url: `${environment.apiUrl}${environment.agentEndpoint}`,
        threadId,
        headers: { 'X-User-Id': environment.userId },
        initialMessages: latestUserMsg,
        initialState: this.sharedState.agentContext(),
      });

      // Start streaming
      this.chatState.isStreaming.set(true);

      // Set stream timeout to prevent infinite hangs
      this.streamTimeout = setTimeout(() => {
        console.warn(`Agent stream timeout after ${this.STREAM_TIMEOUT_MS / 1000}s, aborting`);
        this.cancel();
        this.chatState.setError('Agent response timed out — please try again');
      }, this.STREAM_TIMEOUT_MS);

      // Run agent with typed subscriber callbacks
      await this.agent.runAgent(
        {
          tools: [],
          context: [],
          forwardedProps: {},
        },
        this.buildSubscriber(),
      );
    } catch (error: any) {
      this.clearStreamTimeout();
      // Suppress noisy AGUIError when library sends RUN_FINISHED after RUN_ERROR
      const msg = error?.message || '';
      if (msg.includes('The run has already errored')) {
        return;
      }
      console.error('Agent error:', error);
      this.chatState.setError(msg || 'Failed to connect to agent');
      this.chatState.isStreaming.set(false);
    }
  }

  /**
   * Clear the stream timeout if active
   */
  private clearStreamTimeout(): void {
    if (this.streamTimeout) {
      clearTimeout(this.streamTimeout);
      this.streamTimeout = null;
    }
  }

  /**
   * Cancel the current agent stream
   */
  cancel(): void {
    this.clearStreamTimeout();
    this.agent.abortRun();
    this.chatState.finalizeStreamingMessage();
    this.chatState.isStreaming.set(false);
  }

  /**
   * Build a typed AgentSubscriber — replaces the manual switch(event.type).
   * Each callback receives typed event data and accumulated buffers from the library.
   */
  private buildSubscriber(): AgentSubscriber {
    return {
      // ── Logging (fires for every event) ────────────────────────
      onEvent: ({ event }) => {
        console.log('AG-UI Event:', event.type, event);
      },

      // ── Lifecycle ─────────────────────────────────────────────
      onRunStartedEvent: () => {
        this.chatState.isStreaming.set(true);
      },

      onRunFinishedEvent: () => {
        this.chatState.isStreaming.set(false);
      },

      onRunErrorEvent: ({ event }) => {
        // Suppress user-initiated abort — not an actual error
        if (('code' in event && (event as any).code === 'abort') ||
            ('message' in event && String((event as any).message).includes('aborted'))) {
          return;
        }
        if (this.chatState.currentStreamingMessage()) {
          this.chatState.finalizeStreamingMessage();
        }
        const errorMessage = (event as any).error ?? 'Agent error';
        this.chatState.setError(typeof errorMessage === 'string' ? errorMessage : 'Agent error');
        this.chatState.isStreaming.set(false);
      },

      onRunFailed: ({ error }) => {
        this.clearStreamTimeout();
        const msg = error?.message || '';
        if (msg.includes('The run has already errored') || msg.includes('aborted')) {
          return;
        }
        console.error('Agent error:', error);
        this.chatState.setError(msg || 'Failed to connect to agent');
        this.chatState.isStreaming.set(false);
      },

      onRunFinalized: () => {
        this.clearStreamTimeout();
        this.chatState.finalizeStreamingMessage();
        this.chatState.isStreaming.set(false);
      },

      // ── Text message streaming ────────────────────────────────
      onTextMessageStartEvent: () => {
        this.chatState.startAssistantMessage();
      },

      onTextMessageContentEvent: ({ event }) => {
        this.chatState.appendStreamingContent(event.delta);
      },

      onTextMessageEndEvent: ({ textMessageBuffer }) => {
        // Check if the completed message is raw chart JSON (not meant for display).
        const streamingMsg = this.chatState.currentStreamingMessage();
        if (streamingMsg && this.isChartJsonContent(textMessageBuffer)) {
          this.chatState.removeMessage(streamingMsg.id);
          this.chatState.currentStreamingMessage.set(null);
          this.chatState.isStreaming.set(false);
        } else {
          this.chatState.finalizeStreamingMessage();
        }
      },

      // ── Tool calls ────────────────────────────────────────────
      onToolCallStartEvent: ({ event }) => {
        this.chatState.addToolCall({
          toolName: event.toolCallName,
          status: 'running',
        });
      },

      onToolCallArgsEvent: ({ toolCallName, partialToolCallArgs }) => {
        this.chatState.addToolCall({
          toolName: toolCallName,
          status: 'running',
          arguments: partialToolCallArgs,
        });
      },

      onToolCallEndEvent: ({ toolCallName }) => {
        this.chatState.addToolCall({
          toolName: toolCallName,
          status: 'complete',
        });
      },

      onToolCallResultEvent: ({ event }) => {
        // Check for A2UI visualization payload in content
        const content = (event as any).content;
        if (!content) return;

        try {
          const parsed = typeof content === 'string' ? JSON.parse(content) : content;
          if (parsed?.a2ui === true && parsed.surfaceId && Array.isArray(parsed.messages)) {
            this.a2uiEventService.handleA2UIMessages(parsed.surfaceId, parsed.messages);
          }
        } catch {
          // Not JSON or not A2UI payload — ignore
        }
      },

      // ── State sync (library auto-applies patches via fast-json-patch) ──
      onStateDeltaEvent: ({ agent }) => {
        this.sharedState.syncFromAgent(agent.state);
      },

      onStateSnapshotEvent: ({ agent }) => {
        this.sharedState.syncFromAgent(agent.state);
      },

      // ── Custom events (A2UI surface updates) ──────────────────
      onCustomEvent: ({ event }) => {
        if (event.name === 'a2ui_surface_update') {
          const data = (event as any).data;
          if (data?.surfaceId && Array.isArray(data.messages)) {
            this.a2uiEventService.handleA2UIMessages(data.surfaceId, data.messages);
          }
        }
      },
    };
  }

  /**
   * Detect if message content is raw chart JSON config (not user-facing text).
   * Handles both pure JSON and content where JSON is wrapped with minor
   * surrounding text or markdown fences.
   */
  private isChartJsonContent(content: string): boolean {
    if (!content || !content.trim()) return false;

    const jsonCandidate = this.extractJsonObject(content);
    if (!jsonCandidate) return false;

    try {
      const parsed = JSON.parse(jsonCandidate);
      if (!parsed || typeof parsed !== 'object') return false;

      // Chart configuration: has chart_type/graphType + data keys
      if (
        ('chart_type' in parsed || 'graphType' in parsed) &&
        ('labels' in parsed || 'datasets' in parsed || 'data' in parsed)
      ) {
        return true;
      }

      // Chart reference map: all keys match "chart-XXXX" pattern with string values
      const keys = Object.keys(parsed);
      if (
        keys.length > 0 &&
        keys.every((k) => /^chart-/.test(k) && typeof parsed[k] === 'string')
      ) {
        return true;
      }

      return false;
    } catch {
      return false;
    }
  }

  /**
   * Extract a JSON object string from content that may have surrounding text.
   * Returns the JSON substring if found, or null.
   */
  private extractJsonObject(content: string): string | null {
    let trimmed = content.trim();

    // Pure JSON case (most common)
    if (trimmed.startsWith('{') && trimmed.endsWith('}')) {
      return trimmed;
    }

    // Strip markdown code fences: ```json ... ``` or ``` ... ```
    const fenceMatch = trimmed.match(/```(?:json)?\s*(\{[\s\S]*\})\s*```/);
    if (fenceMatch) {
      return fenceMatch[1].trim();
    }

    // Find the outermost { ... } in the content
    const firstBrace = trimmed.indexOf('{');
    const lastBrace = trimmed.lastIndexOf('}');
    if (firstBrace !== -1 && lastBrace > firstBrace) {
      return trimmed.substring(firstBrace, lastBrace + 1);
    }

    return null;
  }
}
